<a href="https://colab.research.google.com/github/k3robotics/ML-Essentials/blob/main/IntroToLinAlg/IntroToLinAlg.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###*Machine Learning Foundations* - Intro to Linear Algebra

####Data Structures for Algebra

Scalars (Rank 0 Tensors) in Base Python

In [26]:
x = 25
x

25

In [27]:
type(x) # if more specificity is needed (i.e., int16, unint8), use Numpy

int

In [28]:
y = 3

In [29]:
# If you add an int and an int you get a type int as the result
py_sum = x + y
py_sum

28

In [30]:
type(py_sum)

int

In [31]:
# If you add a float and an int you get a type float as the result
x_float = 25.0
float_sum = x_float + y
float_sum

28.0

In [32]:
type(float_sum)

float

###Scalars in PyTorch

*  PyTorch and Tensorflow are the two most popular *automatic differentiation libraries* in Python. Python, of couse, is the most popular programming language in Machine Learning (ML).

*  PyTorch tensors are designed to be pythonic, i.e., to feel and behave like NumPy arrays.

*  The advantage of PyTorch tensors relative to Numpy arrays is that they can be easily used for operations on GPUs.

In [33]:
import torch

In [34]:
x_pt = torch.tensor(25) # type specification optional -> torch.tensor(25, dtype=torch.float16)
x_pt

tensor(25)

In [35]:
x_pt.shape # 0 dimensions

torch.Size([])

#### Scalars in TensorFlow (v2.0 or later)

Tensors created with a wrapper

  *  `tf.Variable`
  *  `tf.constant`
  *  `tf.placeholder`
  *  `tf.SparseTensor`

The most commonly used is `tf.Variable`.

Along with TF tensors, in PyTorch we can also perform operations and convert to and from NumPy arrays.

In [36]:
import tensorflow as tf

In [37]:
x_tf = tf.Variable(25, dtype=tf.int16) # dtype is optional
x_tf

<tf.Variable 'Variable:0' shape=() dtype=int16, numpy=25>

In [38]:
x_tf.shape

TensorShape([])

In [39]:
y_tf = tf.Variable(3, dtype=tf.int16)

In [40]:
x_tf + y_tf # operator overload - being able to use base python `+` to add two tf tensors also(Numpy, PyTorch)

<tf.Tensor: shape=(), dtype=int16, numpy=28>

In [41]:
tf_sum = tf.add(x_tf, y_tf)
tf_sum

<tf.Tensor: shape=(), dtype=int16, numpy=28>

In [42]:
tf_sum.numpy() # Numpy operations automatically convert tensors to NumPy arrays and vice versa.

28

In [43]:
type(tf_sum.numpy())

numpy.int16

In [44]:
tf_float = tf.Variable(25, dtype=tf.float16)
tf_float

<tf.Variable 'Variable:0' shape=() dtype=float16, numpy=25.0>

#### Vectors
*  One dimensional array of numbers
*  Denoted in lowercase, italics, bold, e.g.: **x**
*  Vector elements are arranged in an order, so an element can be accessed by its` index.
  *  The elements of the vector are scalars, not bold, such as $x_{2}$
*  A vector represents a point in space:
  *  A vector of length two represents a location in a 2D matrix. Example: $[x_{1}\ \ x_{2}] = [12\ \ 4]$
  *  A vector with length three represents a location in a 3D cube.
  *  A vector with length n represents a location in a n-dimensional tensor.

#### Vectors (Rank 1 Tensors) in NumPy

In [45]:
import numpy as np

* Note: We need numpy or some other numerical library such as tensor flow or pytorch because we cannot create arrays in base python.

In [46]:
x = np.array([25, 2, 5]) # dtype is optional dtype=np.float16
x

array([25,  2,  5])

In [47]:
len(x)

3

In [48]:
x.shape

(3,)

In [49]:
type(x)

numpy.ndarray

In [50]:
x[0]

25

In [51]:
type(x[0])

numpy.int64

#### Vector Transposition

In [52]:
# Transposing a regular 1-D array has no effect.
x_t = x.T
x_t

array([25,  2,  5])

In [53]:
x_t.shape

(3,)

In [54]:
# There is a change when we use the nested "matrix-style" brackets:
# This gives us an extra dimension. Like working with a matrix.
y = np.array([[25, 2, 5]])
y

array([[25,  2,  5]])

In [55]:
y.shape

(1, 3)

In [56]:
# We can transpose a matrix with a dimensional length 1.
# Now it is a column vector.
y_t = y.T
y_t

array([[25],
       [ 2],
       [ 5]])

In [57]:
y_t.shape # This is now a column vector with 3 rows and 1 column

(3, 1)

In [58]:
# Transpose back to a row vector.
y_t.T

array([[25,  2,  5]])

In [59]:
y_t.T.shape

(1, 3)

#### Zero Vectors
Zero vectors have no effect if added to another vector

In [60]:
z = np.zeros(3)
z

array([0., 0., 0.])

#### Vectors in PyTorch and TensorFlow

In [68]:
x_pt = torch.tensor([25, 2, 5])
x_pt

tensor([25,  2,  5])

In [69]:
x_tf = tf.Variable([25, 2, 5])
x_tf

<tf.Variable 'Variable:0' shape=(1, 3) dtype=int32, numpy=array([[25,  2,  5]], dtype=int32)>